services:
  app:
    build:
      context: ./dev
      dockerfile: Dockerfile
    image: deltafeniks/delta:v1.0.1  
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000" ]

    environment:
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - CLIENT_ID=${CLIENT_ID}
    secrets:
      - secret_id

    volumes:
      - ./log:/usr/src/app/fastapi.log 

    depends_on:
      - db
    networks:
      - proxy  
    expose:
      - 8000


  db:
    image: mysql:8.0.43-debian
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - proxy
    expose:
      - 3306
    volumes:
      - db_data:/var/lib/mysql
    restart: on-failure:5

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
      - ./etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`api.deltafeniks.kz`)"
      - "traefik.http.routers.nginx.entrypoints=https"
      - "traefik.http.routers.nginx.tls.certresolver=myresolver"
    restart: always  
    depends_on:
      - app

secrets:
  secret_id:
    file: ./sets/temp_app.txt


volumes:
  db_data:

networks:
  proxy:
    external: true